---
apiVersion: v1
kind: Secret
metadata:
  name: backup-restore-sidecar-backup-provider-config
type: Opaque
stringData:
  bucketName: backup-sidecar-test 
  bucketLocation: europe-west3
  projectID: <your-gcp-project-id>
  serviceaccount.json: |
    <your service account credentials>
